import type { OpenApiEndpoint } from '../../types/openapi';

// Reviewed expectations, kept independent of the live document's declarations.
export const publicOperations = [
  ['post', '/api/v1/users/sso/exchange'],
  ['post', '/api/v1/users/signup'],
  ['post', '/api/v1/users/signin'],
  ['post', '/api/v1/users/signin/2fa'],
  ['post', '/api/v1/users/refresh'],
  ['post', '/api/v1/users/password/reset'],
  ['post', '/api/v1/users/password/forgot'],
  ['get', '/api/v1/traffic/logs'],
  ['get', '/api/v1/traffic/logs/{correlationId}'],
  ['get', '/api/v1/traffic/info'],
] as const satisfies readonly OpenApiEndpoint[];

export const protectedOperations = [
  ['get', '/api/v1/users/{username}'],
  ['put', '/api/v1/users/{username}'],
  ['delete', '/api/v1/users/{username}'],
  ['get', '/api/v1/users/tool-system-prompt'],
  ['put', '/api/v1/users/tool-system-prompt'],
  ['get', '/api/v1/users/chat-system-prompt'],
  ['put', '/api/v1/users/chat-system-prompt'],
  ['get', '/api/v1/products/{id}'],
  ['put', '/api/v1/products/{id}'],
  ['delete', '/api/v1/products/{id}'],
  ['put', '/api/v1/orders/{id}/status'],
  ['put', '/api/v1/cart/items/{productId}'],
  ['delete', '/api/v1/cart/items/{productId}'],
  ['post', '/api/v1/users/logout'],
  ['post', '/api/v1/users/2fa/setup'],
  ['post', '/api/v1/users/2fa/recovery-codes'],
  ['post', '/api/v1/users/2fa/disable'],
  ['post', '/api/v1/users/2fa/confirm'],
  ['post', '/api/v1/qr/create'],
  ['get', '/api/v1/products'],
  ['post', '/api/v1/products'],
  ['get', '/api/v1/orders'],
  ['post', '/api/v1/orders'],
  ['post', '/api/v1/orders/{id}/cancel'],
  ['post', '/api/v1/ollama/generate'],
  ['post', '/api/v1/ollama/chat'],
  ['post', '/api/v1/ollama/chat/tools'],
  ['post', '/api/v1/email'],
  ['post', '/api/v1/cart/items'],
  ['post', '/api/v1/admin/inventory/{productId}/adjustments'],
  ['get', '/api/v1/users'],
  ['get', '/api/v1/users/me'],
  ['get', '/api/v1/users/me/email-events'],
  ['get', '/api/v1/users/2fa/status'],
  ['get', '/api/v1/orders/{id}'],
  ['get', '/api/v1/orders/admin'],
  ['get', '/api/v1/ollama/chat/tools/definitions'],
  ['get', '/api/v1/cart'],
  ['delete', '/api/v1/cart'],
  ['get', '/api/v1/admin/inventory'],
  ['get', '/api/v1/admin/inventory/{productId}'],
  ['get', '/api/v1/admin/inventory/{productId}/movements'],
  ['delete', '/api/v1/users/{username}/right-to-be-forgotten'],
] as const satisfies readonly OpenApiEndpoint[];
